<?php

/**
 * BaseProduct
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $code
 * @property string $title
 * @property string $body
 * @property string $image
 * @property string $big_image
 * @property boolean $is_published
 * @property integer $position
 * @property boolean $popular
 * @property Doctrine_Collection $Categories
 * @property Doctrine_Collection $LinkingProductCategory
 * 
 * @method integer             getId()                     Returns the current record's "id" value
 * @method string              getCode()                   Returns the current record's "code" value
 * @method string              getTitle()                  Returns the current record's "title" value
 * @method string              getBody()                   Returns the current record's "body" value
 * @method string              getImage()                  Returns the current record's "image" value
 * @method string              getBigImage()               Returns the current record's "big_image" value
 * @method boolean             getIsPublished()            Returns the current record's "is_published" value
 * @method integer             getPosition()               Returns the current record's "position" value
 * @method boolean             getPopular()                Returns the current record's "popular" value
 * @method Doctrine_Collection getCategories()             Returns the current record's "Categories" collection
 * @method Doctrine_Collection getLinkingProductCategory() Returns the current record's "LinkingProductCategory" collection
 * @method Product             setId()                     Sets the current record's "id" value
 * @method Product             setCode()                   Sets the current record's "code" value
 * @method Product             setTitle()                  Sets the current record's "title" value
 * @method Product             setBody()                   Sets the current record's "body" value
 * @method Product             setImage()                  Sets the current record's "image" value
 * @method Product             setBigImage()               Sets the current record's "big_image" value
 * @method Product             setIsPublished()            Sets the current record's "is_published" value
 * @method Product             setPosition()               Sets the current record's "position" value
 * @method Product             setPopular()                Sets the current record's "popular" value
 * @method Product             setCategories()             Sets the current record's "Categories" collection
 * @method Product             setLinkingProductCategory() Sets the current record's "LinkingProductCategory" collection
 * 
 * @package    LavishingBeaty
 * @subpackage model
 * @author     Tsvetan Himchev
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProduct extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('product');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('code', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('body', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('big_image', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('is_published', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => true,
             ));
        $this->hasColumn('position', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('popular', 'boolean', null, array(
             'type' => 'boolean',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Category as Categories', array(
             'refClass' => 'LinkingProductCategory',
             'local' => 'product_id',
             'foreign' => 'category_id'));

        $this->hasMany('LinkingProductCategory', array(
             'local' => 'id',
             'foreign' => 'product_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'title',
              1 => 'body',
              2 => 'image',
              3 => 'big_image',
              4 => 'is_published',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($i18n0);
    }
}