<?php

/**
 * BaseBanner
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $image
 * @property string $link
 * @property string $title
 * @property string $body
 * @property boolean $is_published
 * @property integer $position
 * 
 * @method integer getId()           Returns the current record's "id" value
 * @method string  getImage()        Returns the current record's "image" value
 * @method string  getLink()         Returns the current record's "link" value
 * @method string  getTitle()        Returns the current record's "title" value
 * @method string  getBody()         Returns the current record's "body" value
 * @method boolean getIsPublished()  Returns the current record's "is_published" value
 * @method integer getPosition()     Returns the current record's "position" value
 * @method Banner  setId()           Sets the current record's "id" value
 * @method Banner  setImage()        Sets the current record's "image" value
 * @method Banner  setLink()         Sets the current record's "link" value
 * @method Banner  setTitle()        Sets the current record's "title" value
 * @method Banner  setBody()         Sets the current record's "body" value
 * @method Banner  setIsPublished()  Sets the current record's "is_published" value
 * @method Banner  setPosition()     Sets the current record's "position" value
 * 
 * @package    LavishingBeaty
 * @subpackage model
 * @author     Tsvetan Himchev
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBanner extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('banner');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('link', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('title', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('body', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('is_published', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
        $this->hasColumn('position', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 1,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'image',
              1 => 'link',
              2 => 'title',
              3 => 'body',
              4 => 'position',
              5 => 'is_published',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($i18n0);
    }
}