<?php

/**
 * BaseSlider_image
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $image
 * @property string $link
 * @property boolean $is_published
 * @property Doctrine_Collection $Categories
 * @property Doctrine_Collection $LinkingSliderCategory
 * 
 * @method integer             getId()                    Returns the current record's "id" value
 * @method string              getImage()                 Returns the current record's "image" value
 * @method string              getLink()                  Returns the current record's "link" value
 * @method boolean             getIsPublished()           Returns the current record's "is_published" value
 * @method Doctrine_Collection getCategories()            Returns the current record's "Categories" collection
 * @method Doctrine_Collection getLinkingSliderCategory() Returns the current record's "LinkingSliderCategory" collection
 * @method Slider_image        setId()                    Sets the current record's "id" value
 * @method Slider_image        setImage()                 Sets the current record's "image" value
 * @method Slider_image        setLink()                  Sets the current record's "link" value
 * @method Slider_image        setIsPublished()           Sets the current record's "is_published" value
 * @method Slider_image        setCategories()            Sets the current record's "Categories" collection
 * @method Slider_image        setLinkingSliderCategory() Sets the current record's "LinkingSliderCategory" collection
 * 
 * @package    LavishingBeaty
 * @subpackage model
 * @author     Tsvetan Himchev
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSlider_image extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('slider_image');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('link', 'string', null, array(
             'type' => 'string',
             'notnull' => true,
             ));
        $this->hasColumn('is_published', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Category as Categories', array(
             'refClass' => 'LinkingSliderCategory',
             'local' => 'slider_image_id',
             'foreign' => 'category_id'));

        $this->hasMany('LinkingSliderCategory', array(
             'local' => 'id',
             'foreign' => 'slider_image_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'image',
              1 => 'link',
              2 => 'is_published',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($i18n0);
    }
}