<?php

/**
 * BasePage
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $title
 * @property string $image
 * @property string $body
 * @property string $links
 * @property string $partners
 * @property string $meta_title
 * @property string $meta_keywords
 * @property string $meta_description
 * @property boolean $is_published
 * @property integer $type
 * @property integer $position
 * 
 * @method integer getId()               Returns the current record's "id" value
 * @method string  getTitle()            Returns the current record's "title" value
 * @method string  getImage()            Returns the current record's "image" value
 * @method string  getBody()             Returns the current record's "body" value
 * @method string  getLinks()            Returns the current record's "links" value
 * @method string  getPartners()         Returns the current record's "partners" value
 * @method string  getMetaTitle()        Returns the current record's "meta_title" value
 * @method string  getMetaKeywords()     Returns the current record's "meta_keywords" value
 * @method string  getMetaDescription()  Returns the current record's "meta_description" value
 * @method boolean getIsPublished()      Returns the current record's "is_published" value
 * @method integer getType()             Returns the current record's "type" value
 * @method integer getPosition()         Returns the current record's "position" value
 * @method Page    setId()               Sets the current record's "id" value
 * @method Page    setTitle()            Sets the current record's "title" value
 * @method Page    setImage()            Sets the current record's "image" value
 * @method Page    setBody()             Sets the current record's "body" value
 * @method Page    setLinks()            Sets the current record's "links" value
 * @method Page    setPartners()         Sets the current record's "partners" value
 * @method Page    setMetaTitle()        Sets the current record's "meta_title" value
 * @method Page    setMetaKeywords()     Sets the current record's "meta_keywords" value
 * @method Page    setMetaDescription()  Sets the current record's "meta_description" value
 * @method Page    setIsPublished()      Sets the current record's "is_published" value
 * @method Page    setType()             Sets the current record's "type" value
 * @method Page    setPosition()         Sets the current record's "position" value
 * 
 * @package    LavishingBeaty
 * @subpackage model
 * @author     Tsvetan Himchev
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePage extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('page');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('title', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('image', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('body', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('links', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('partners', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('meta_title', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('meta_keywords', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('meta_description', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('is_published', 'boolean', null, array(
             'type' => 'boolean',
             'notnull' => true,
             'default' => true,
             ));
        $this->hasColumn('type', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 4,
             ));
        $this->hasColumn('position', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 1,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $i18n0 = new Doctrine_Template_I18n(array(
             'fields' => 
             array(
              0 => 'title',
              1 => 'body',
              2 => 'links',
              3 => 'partners',
              4 => 'image',
              5 => 'is_published',
              6 => 'meta_title',
              7 => 'meta_keywords',
              8 => 'meta_description',
             ),
             ));
        $this->actAs($timestampable0);
        $this->actAs($i18n0);
    }
}