default:
  http_metas:
    content-type: text/html

  metas:
    title:        Vertinity - Admin Panel
    description:  Vertinity - Admin Panel
    keywords:     Vertinity, Admin Panel
    language:     en
    #robots:       index, follow

  stylesheets:    []

  javascripts:    []

  has_layout:     true
  layout:         layout
