<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2014/03/10 18:38:50

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=lb',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
