<?php
// auto-generated by sfDefineEnvironmentConfigHandler
// date: 2014/03/10 18:38:49
sfConfig::add(array(
  'app_salt' => 'h&lL0Be@u7ifUlWorL6',
  'app_contact_email' => 'mail@creaton.bg',
  'app_receiver_email' => 'mail@creaton.bg',
  'app_cookie_settings' => array (
  'name' => 'ff_cookie',
  'days' => 14,
),
  'app_roles' => array (
  'admin' => 'Administrator',
),
  'app_supported_languages' => array (
  'en' => 'English',
),
  'app_page_types' => array (
  0 => 'Undefined',
  1 => 'Homepage',
  2 => 'About us',
  3 => 'Categories',
  4 => 'Products',
  5 => 'Articles',
  6 => 'Contact us',
  7 => 'FAQ',
  8 => 'Terms and conditions',
),
  'app_translated_page_types' => array (
  0 => 'Undefined',
  1 => 'Homepage',
  2 => 'About us',
  3 => 'Categories',
  4 => 'Products',
  5 => 'Articles',
  6 => 'Contact us',
  7 => 'FAQ',
  8 => 'Terms and conditions',
),
  'app_homepage_slider_image' => array (
  'width' => 654,
  'height' => 314,
),
  'app_page_wide_image' => array (
  'width' => 200,
  'height' => 100,
),
  'app_page_image' => array (
  'width' => 200,
  'height' => 100,
),
  'app_article_thumb_image' => array (
  'width' => 136,
  'height' => 136,
),
  'app_publication_thumb_image' => array (
  'width' => 180,
  'height' => 240,
),
  'app_product_big_image' => array (
  'width' => 580,
  'height' => 354,
),
  'app_banner_thumb_image' => array (
  'width' => 184,
  'height' => 91,
),
  'app_thumb_image' => array (
  'width' => 136,
  'height' => 136,
),
  'app_records_per_page' => 5,
));
