<?php

/**
 * AppVarTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AppVarTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AppVarTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('AppVar');
    }
}