<?php

/**
 * Article
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    osteo_cardics
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Article extends BaseArticle {

    public function delete(Doctrine_Connection $conn = null) {
        $filename = sfConfig::get('sf_upload_dir') . '/articles/' . $this->getImage();
        if (file_exists($filename)) {
            @unlink($filename);
        }
        return parent::delete($conn);
    }

}