<?php

/**
 * Banner
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    LavishingBeaty
 * @subpackage model
 * @author     Tsvetan Himchev
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Banner extends BaseBanner
{
    public function delete(Doctrine_Connection $conn = null) {
        $filename = sfConfig::get('sf_upload_dir') . '/banners/' . $this->getImage();
        if (file_exists($filename)) {
            @unlink($filename);
        }
        return parent::delete($conn);
    }
}