<?php

/**
 * CategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Category');
    }
    public function getNextPosition() {
		$position = Doctrine_Query::create()
			->select('MAX(position)')
			->from('Category')
			->fetchOne(array(), Doctrine_Core::HYDRATE_SINGLE_SCALAR);
		if (!$position) {
			return 1;
		}
		return $position + 1;
	}
}