<?php

/**
 * LinkingSliderCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LinkingSliderCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LinkingSliderCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LinkingSliderCategory');
    }
}