<?php

/**
 * LinkingProductCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LinkingProductCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LinkingProductCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LinkingProductCategory');
    }
}