<?php

/**
 * PageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PageTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object PageTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('Page');
  }
  
  public function getPageByType($type)
  {
    $page = $this->createQuery()
            ->where('type = ?', $type)
            ->limit(1)
            ->fetchOne();
    if (!$page) {
      $page = new Page();
      $page->setType($type);
    }
    return $page;
  }
  
  public function getListingQuery($type, $orderBy)
  {
    return $this->createQuery('a')
            ->leftJoin('a.Translation t')
            ->where('a.type = ?', $type)
            ->andWhere('t.lang = ?', sfContext::getInstance()->getUser()->getCulture())
            ->orderBy($orderBy);
  }
  
  public function getNextPosition($type) {
    $position = Doctrine_Query::create()
            ->select('MAX(position)')
            ->from('Page')
            ->where('type = ?', $type)
            ->fetchOne(array(), Doctrine_Core::HYDRATE_SINGLE_SCALAR);
    if (!$position) {
      return 1;
    }
    return $position + 1;
  }
}