<?php

/**
 * Page
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    cmp
 * @subpackage model
 * @author     St2
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Page extends BasePage
{
    public function delete(Doctrine_Connection $conn = null) {
        $filename = sfConfig::get('sf_upload_dir') . '/pages/' . $this->getImage();
        if (file_exists($filename)) {
            @unlink($filename);
        }
        return parent::delete($conn);
    }
}
