<?php

/**
 * ProductTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProductTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object ProductTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Product');
    }

    public function getListingQuery($filters) {
        $query = $this->createQuery('a')->leftJoin('a.Translation t');
        if (isset($filters['search_text']) && $filters['search_text']) {
            $search = '%' . $filters['search_text'] . '%';
            $query->where('t.title LIKE ?', $search);
        }
        if (isset($filters['category']) && $filters['category']) {
            $query->where('category_id = ?', $filters['category']);
        }
        
        return $query;
    }
    public function getNextPosition() {
		$position = Doctrine_Query::create()
			->select('MAX(position)')
			->from('Product')
			->fetchOne(array(), Doctrine_Core::HYDRATE_SINGLE_SCALAR);
		if (!$position) {
			return 1;
		}
		return $position + 1;
	}

}