<?php

/**
 * Product
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    osteo_cardics
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Product extends BaseProduct
{
    public function delete(Doctrine_Connection $conn = null) {
        $filename = sfConfig::get('sf_upload_dir') . '/products/' . $this->getImage();
        if (file_exists($filename)) {
            @unlink($filename);
        }
        return parent::delete($conn);
    }
    public function moveUp() {
    $previous_record = Doctrine::getTable('Product')->createQuery()
            ->where('position < ?', array($this->getPosition()))
            ->orderBy('position DESC')
            ->limit(1)
            ->fetchOne();
    
    if ($previous_record) {
      $new_position = $previous_record->getPosition();
      $previous_record->setPosition($this->getPosition());
      $this->setPosition($new_position);
      $this->save();
      $previous_record->save();
    }
  }
  
  public function moveDown() {
    $next_record = Doctrine::getTable('Product')->createQuery()
            ->where('position > ?', array($this->getPosition()))
            ->orderBy('position')
            ->limit(1)
            ->fetchOne();
    
    if ($next_record) {
      $new_position = $next_record->getPosition();
      $next_record->setPosition($this->getPosition());
      $this->setPosition($new_position);
      $this->save();
      $next_record->save();
    }
  }
}