<?php

/**
 * Slider_imageTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Slider_imageTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object Slider_imageTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Slider_image');
    }
}