<?php

/**
 * UserSessionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UserSessionTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object UserSessionTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('UserSession');
  }
  
  public function getListingQuery(Array $filters, $orderBy = 'created_at DESC') {
    $query = $this->createQuery();
    if (isset($filters['email']) && $filters['email']) {
      $query->andWhere('name LIKE ?', '%' . $filters['email'] . '%');
    }
    if (isset($filters['ip']) && $filters['ip']) {
      $query->andWhere('ip LIKE ?', '%' . $filters['ip'] . '%');
    }
    if (isset($filters['browser_info']) && $filters['browser_info']) {
      $query->andWhere('browser_info LIKE ?', '%' . $filters['browser_info'] . '%');
    }
    if (isset($filters['date']) && $filters['date']) {
      if (isset($filters['date']['from']) && is_array($filters['date']['from'])) {
        $from = array_filter($filters['date']['from']);
        if (count($from) == 3) {
          $from_date = $from['year'] . '-' . $from['month'] . '-' . $from['day'] . ' 00:00:01';
          $query->andWhere('created_at >= ?', $from_date);
        }
      }
      if (isset($filters['date']['to']) && is_array($filters['date']['to'])) {
        $to = array_filter($filters['date']['to']);
        if (count($to) == 3) {
          $to_date = $to['year'] . '-' . $to['month'] . '-' . $to['day'] . ' 23:59:59';
          $query->andWhere('created_at <= ?', $to_date);
        }
      }
    }
    $query->orderBy($orderBy);
    return $query;
  }
}