# Settings
AppVar:
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    var_key:
      type: string(255)
      notnull: true
    var_value:
      type: string

# User management
User:
  actAs: [Timestampable]
  columns:
    id:
      type: integer(4),
      primary: true,
      autoincrement: true
    parent_id:
      type: integer(4)
    email:
      type: string(255)
      notnull: true
      unique: true
    password:
      type: string(40)
      notnull: true
    remember_key:
      type: string(32)
    name:
      type: string(255)
      notnull: true
    role:
      type: string(255)
      notnull: true
      default: user
    is_active:
      type: boolean
      notnull: true
      default: false
  relations:
    Parent: { onDelete: CASCADE, class: User, local: parent_id, foreign: id, foreignAlias: Users }

UserSession:
  options:
    type: MyISAM
    symfony:
      form: false
  actAs: [Timestampable]
  columns:
    id:
      type: integer(4),
      primary: true,
      autoincrement: true
    user_id:
      type: integer(4)
    name:
      type: string(255)
    ip:
      type: string(255)
    browser_info:
      type: string

# CMS
Page:
  actAs:
    Timestampable: ~
    I18n:
      fields: [title, body, links, partners, image, is_published, meta_title, meta_keywords, meta_description]
  columns:
    id:
      type: integer(4),
      primary: true,
      autoincrement: true
    title:
      type: string(255)
    image:
      type: string(255)
    body:
      type: string
    links:
      type: string
    partners:
      type: string
    meta_title:
      type: string
    meta_keywords:
      type: string
    meta_description:
      type: string
    is_published:
      type: boolean
      notnull: true
      default: true
    type:
      type: integer(4)
      notnull: true
      default: 0
    position:
      type: integer(4)
      notnull: true
      default: 1
#product      
Product: 
  actAs:
    Timestampable: ~
    I18n:
      fields: [title, body, image, big_image, is_published]
  columns:
    id:
      type: integer(4),
      primary: true,
      autoincrement: true
    code:
      type: string(255)
    title:
      type: string(255)
      notnull: true
    body:
      type: string
    image:
      type: string(255)
    big_image:
      type: string(255)
    is_published:
      type: boolean
      notnull: true
      default: true 
    position:
      type: integer(4)
    popular:
      type: boolean
  relations:
    Categories:
      class: Category
      local: product_id
      foreign: category_id 
      refClass: LinkingProductCategory

#Category
Category:
  actAs:
    Timestampable: ~
    I18n:
      fields: [title, body, big_body, is_published]
  columns:
    id:
      type: integer(4),
      primary: true,
      autoincrement: true
    parrent_id:
      type: integer(4)  
    title:
      type: string(255)
      notnull: true
    body:
      type: string
    big_body:
      type: string
    is_published:
      type: boolean
      notnull: true
      default: true
    icon:
      type: string(255)
    position:
      type: integer(4)  
#product to category

LinkingProductCategory:
  columns:
    product_id:  { type: integer(4), notnull: true }
    category_id: { type: integer(4), notnull: true }
  relations:
    Products:
      class:    Product
      local:    product_id
      foreign:  id
      onDelete: CASCADE
      onUpdate: CASCADE
    Categories:
      class:    Category
      local:    category_id
      foreign:  id
      onDelete: CASCADE
      onUpdate: CASCADE
      
#Article
Article:
  actAs:
    Timestampable: ~
    I18n:
      fields: [title, short_body, author, source, body, image, big_image, is_published]
  columns:
    id:
      type: integer(4),
      primary: true,
      autoincrement: true
    title:
      type: string(255)
      notnull: true
    short_body:
      type: string
    body:
      type: string
    author:
      type: string(255)
    source: 
      type: string
    image:
      type: string(255)
    big_image:
      type: string(255)
    popular:
      type: boolean
    is_published:
      type: boolean
      notnull: true
      default: true
    position:
      type: integer(4)
    viewed:
      type: integer(5)
      
#Slider images
Slider_image:
  actAs:
    Timestampable: ~
    I18n:
      fields: [image, link, is_published]
  columns:
    id:
      type: integer(4),
      primary: true,
      autoincrement: true
    image:
      type: string(255)
      notnull: true
    link:
      type: string
      notnull: true  
    is_published:
      type: boolean
      notnull: true
      default: true
  relations:
    Categories:
      class: Category
      refClass: LinkingSliderCategory
      local: slider_image_id
      foreign: category_id

LinkingSliderCategory:
  columns:
    slider_image_id:  { type: integer(4), notnull: true }
    category_id: { type: integer(4), notnull: true }
  relations:
    Slider_images:
      class:    Slider_image
      local:    slider_image_id
      foreign:  id
      onDelete: cascade
    Categories:
      class:    Category
      local:    category_id
      foreign:  id
      onDelete: cascade
 
Banner:
   actAs:
    Timestampable: ~
    I18n:
      fields: [image, link, title, body, position, is_published]
   columns:
    id:
      type: integer(4),
      primary: true,
      autoincrement: true
    image:
      type: string(255)
    link:
      type: string
    title:
      type: string
    body:
      type: string
    is_published:
      type: boolean
      default: true
    position:
      type: integer(4)
      notnull: true
      default: 1  